# Asserts the edge gate (issue #71) is associated with the protected
# behaviour only. This is what stands between the design and a
# distribution-wide Function invocation bill — CloudFront Functions bill per
# invocation, and a distribution-wide association would bill every /status
# poll from every waiter, dominating the cost model at a million waiters
# (ADR-0021 §4.3).
#
# mock_provider avoids needing real AWS credentials in CI: nothing here reads
# live state, it only inspects the plan this module would produce.
#
# Run with: terraform -chdir=infra/modules/edge test

mock_provider "aws" {}

variables {
  name_prefix             = "test"
  api_gateway_domain_name = "api.example.com"
  env                     = "test"
  demo_origin_domain_name = "demo.s3.example.com"
  gate_kvs_arn            = "arn:aws:cloudfront::123456789012:key-value-store/test"
  event_id                = "smoke"
}

run "default_behaviour_carries_the_gate" {
  command = plan

  assert {
    condition = anytrue([
      for fa in aws_cloudfront_distribution.this.default_cache_behavior[0].function_association :
      fa.event_type == "viewer-request"
    ])
    error_message = "the protected default behaviour must associate the gate at viewer-request"
  }
}

run "no_other_behaviour_carries_a_function_association" {
  command = plan

  assert {
    condition = alltrue([
      for b in aws_cloudfront_distribution.this.ordered_cache_behavior : length(b.function_association) == 0
    ])
    error_message = "only the protected default behaviour may carry the gate — a function_association on any ordered_cache_behavior would bill every request on that path per invocation"
  }
}

# The inverse of the assertions above, and the one that actually bit. A path
# with no ordered behaviour of its own falls through to the DEFAULT behaviour,
# which carries the gate — so /v1/join reaching it means the gate refuses every
# visitor who has no session cookie yet, which is every visitor trying to join.
# Nothing else notices: the refusal is a well-formed 403 from the edge and the
# queue simply stays empty.
run "the_join_path_has_its_own_behaviour" {
  command = plan

  assert {
    condition = anytrue([
      for b in aws_cloudfront_distribution.this.ordered_cache_behavior :
      b.path_pattern == "/v1/join"
    ])
    error_message = "/v1/join needs its own ordered_cache_behavior; without one it falls through to the gated default behaviour and nobody can join"
  }
}

# The CloudFront-Viewer-* headers are generated by CloudFront rather than sent
# by the viewer, so the managed AllViewerExceptHostHeader policy the other
# write paths use never forwards them. Join telemetry is silently empty without
# an explicit whitelist, and content-type is what lets API Gateway parse the
# body at all.
#
# Asserted against the policy's own configuration rather than the behaviour's
# origin_request_policy_id, which is not known until apply.
run "the_join_policy_whitelists_the_headers_the_telemetry_needs" {
  command = plan

  assert {
    condition = alltrue([
      for h in [
        "content-type",
        "CloudFront-Viewer-Address",
        "CloudFront-Viewer-ASN",
        "CloudFront-Viewer-Country",
        "CloudFront-Viewer-JA4-Fingerprint",
        ] : contains(
        aws_cloudfront_origin_request_policy.join.headers_config[0].headers[0].items,
        h
      )
    ])
    error_message = "the join origin request policy must whitelist content-type and every CloudFront-Viewer-* header the mapping template reads"
  }
}
