// Cross-language conformance vectors (issue #71): proves the shipped gate.js
// agrees with wr_common::crypto and wr_common::rules::ProtectionRule on both
// credential verification and rule matching.
//
// Vectors are generated by crates/wr-common/tests/vectors.rs, never hand
// typed here — regenerate with
// `cargo test -p wr-common -- --ignored regenerate_vectors` after a wire
// format change.
//
// Positives prove Rust-minted -> JS-verified. Negatives prove the two reject
// the same set (JS never mints, so there is no JS-minted -> Rust-verified
// direction to cover). Rule vectors are the only thing that proves rule
// agreement: Rust's eq_ignore_ascii_case and JS's toLowerCase() diverge on
// non-ASCII input even though both read the same wire encoding.
//
// Run with: node --test infra/modules/edge/tests/*.test.js

"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const { loadGate, event } = require("./vm-gate");

const VECTORS_PATH = path.join(
  __dirname,
  "..",
  "..",
  "..",
  "..",
  "crates",
  "wr-common",
  "tests",
  "vectors",
  "session.json"
);
const KIND_SESSION = 0x02;

const vectors = JSON.parse(fs.readFileSync(VECTORS_PATH, "utf8"));

/**
 * The original secret bytes, as a Buffer. Must stay a Buffer, not a decoded
 * string: `createHmac` reads a string argument as UTF-8, and round-tripping
 * arbitrary bytes through `.toString("binary")` (latin1) only agrees with
 * the original bytes for all-ASCII input — true of the fixed test key here,
 * not of a real `secrets.token_urlsafe` secret in general.
 */
function secretFrom(keyHex) {
  return Buffer.from(keyHex, "hex");
}

test("conformance vectors file is non-empty", () => {
  assert.ok(vectors.positives.length > 0);
  assert.ok(vectors.negatives.length > 0);
  assert.ok(vectors.rules.length > 0);
});

for (const v of vectors.positives) {
  test(`positive: ${v.name}`, () => {
    const gate = loadGate();
    const result = gate.verify(v.credential, KIND_SESSION, secretFrom(v.key_hex));
    assert.notEqual(result, null, `vector ${v.name} was rejected`);
    assert.equal(result.eventId, v.event_id, `vector ${v.name} event id`);
    assert.equal(result.expiresAt, v.expires_at, `vector ${v.name} expires_at`);
  });
}

for (const v of vectors.negatives) {
  test(`negative: ${v.name}`, () => {
    const gate = loadGate();
    const result = gate.verify(v.credential, KIND_SESSION, secretFrom(v.key_hex));
    assert.equal(result, null, `vector ${v.name} was unexpectedly accepted`);
  });
}

for (const v of vectors.rules) {
  test(`rule: ${v.name}`, () => {
    const gate = loadGate();
    const headers = {};
    for (const [k, val] of v.request.headers) {
      headers[k] = { value: val };
    }
    const cookies = {};
    for (const [k, val] of v.request.cookies) {
      cookies[k] = { value: val };
    }
    const request = { uri: v.request.path, headers, cookies };
    assert.equal(gate.matches(v.rule, request), v.matches, `rule vector ${v.name}`);
  });
}

// CloudFront Function size ceiling (ADR-0021 §2): 10,240 bytes, not
// adjustable, and there is no warning band below it — v1's "warn at 9,000"
// framing was a mislabelled hard gate and was withdrawn (ADR-0021 §6). This
// measures the bytes Terraform actually submits: the *rendered* template,
// imports included (vm-gate.js strips the import lines for local execution
// only; the real deployed function keeps them).
test("the rendered function source is under the CloudFront Function size ceiling", () => {
  const SIZE_LIMIT = 10240;
  const templateSrc = fs.readFileSync(
    path.join(__dirname, "..", "functions", "gate.js.tftpl"),
    "utf8"
  );
  const rendered = templateSrc.replace(/\$\{(\w+)\}/g, (_, name) => {
    const values = {
      event_id: "smoke",
      session_cookie_name: "vwr_session",
      waiting_path: "/_wr/waiting.html",
    };
    if (!(name in values)) {
      throw new Error(`missing template value for \${${name}}`);
    }
    return values[name];
  });
  const size = Buffer.byteLength(rendered, "utf8");
  console.log(`gate.js rendered size: ${size} of ${SIZE_LIMIT} bytes (${((size * 100) / SIZE_LIMIT).toFixed(1)}%)`);
  assert.ok(
    size < SIZE_LIMIT,
    `gate.js is ${size} bytes, at or over the ${SIZE_LIMIT}-byte CloudFront Function limit`
  );
});
