[package]
name = "wr-domain"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
wr-permutation = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }

[lints]
workspace = true
