[package]
name = "admin"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[lib]
name = "admin"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
askama = { workspace = true, features = ["std", "derive", "config"] }
aws-config = { workspace = true, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
aws-lc-rs = { workspace = true, features = ["aws-lc-sys"] }
aws-sdk-cloudfrontkeyvaluestore = { workspace = true, features = ["behavior-version-latest", "default-https-client", "rt-tokio", "sigv4a"] }
aws-sdk-dynamodb = { workspace = true, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
aws-sdk-ssm = { workspace = true, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
aws-smithy-types = { workspace = true }
axum = { workspace = true, features = ["http1", "query", "form", "json", "tokio"] }
base64 = { workspace = true, features = ["alloc"] }
cookie = { workspace = true }
jsonwebtoken = { workspace = true, features = ["aws_lc_rs"] }
lambda_http = { workspace = true, features = ["apigw_rest"] }
mime_guess = { workspace = true }
openidconnect = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls-webpki-roots-no-provider", "http2"] }
rust-embed = { workspace = true }
rustls = { workspace = true, features = ["aws_lc_rs", "std", "tls12"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["normalize-path"] }
tracing = { workspace = true, default-features = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "json"] }
wr-common = { workspace = true }

[lints]
workspace = true
