[package]
name = "admin"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[lib]
name = "admin"
path = "src/lib.rs"

[dependencies]
wr-domain = { workspace = true }
lambda_http = { workspace = true, features = ["apigw_rest"] }
axum = { workspace = true, features = ["http1", "query", "form", "tokio"] }
tower = { workspace = true }
askama = { workspace = true, features = ["std", "derive", "config"] }
rust-embed = { workspace = true }
mime_guess = { workspace = true }
aws-config = { workspace = true, features = ["behavior-version-latest"] }
aws-sdk-dynamodb = { workspace = true, features = ["default-https-client", "rt-tokio"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
thiserror = { workspace = true }
tracing = { workspace = true, default-features = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "json"] }
anyhow = { workspace = true, features = ["std"] }

[lints]
workspace = true
