[package]
name = "assign_position"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[lib]
name = "assign_position"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
aws-config = { workspace = true, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
aws-sdk-dynamodb = { workspace = true, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
aws_lambda_events = { workspace = true, features = ["sqs"] }
lambda_runtime = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true, default-features = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "json"] }
wr-common = { workspace = true }

[dev-dependencies]
base64 = { workspace = true, features = ["std"] }
jsonwebtoken = { workspace = true, features = ["aws_lc_rs"] }

[lints]
workspace = true
